### ISSUE TITLE
I volunteer as maintainer, if someone helps me at the start

### ISSUE THREAD

**Issue by silverhook** [YunoHost-Apps/borgwarehouse_ynh#4]
Hi,

I’m interested in having Borg Warehouse up and running and would be willing to pick up the maintainership from @ericgaspar.

That said, this would be my first YuNoHost package, so at least initially I would really need some help learning all the ropes.

**Comment by rmkni** [comment]
Hey, same here, if someone would like to share with 2 people at the same time?

**Comment by silverhook** [comment]
Two noobs, one bug? :sweat_smile:  (SCNR)

**Comment by silverhook** [comment]
@rmkni , from what I can tell, it seems we need to finalise this in order for it to work: https://github.com/YunoHost-Apps/borgwarehouse_ynh/pull/2

**Comment by Limezy** [comment]
I'll try to help you

**Comment by silverhook** [comment]
Awesome, thanks, @Limezy , it seems you’re ahead of everyone else here already.

**Comment by Limezy** [comment]
With pleasure, hope I can help so that after a few updates you'll be autonomous ! However as of now I wasn't able yet to have the app running correctly. Maybe the symlinks aren't good, I'm checking.
