### ISSUE TITLE
Upgrade to BorgWarehouse 2.1.0

### ISSUE THREAD

**Issue by silverhook** [YunoHost-Apps/borgwarehouse_ynh#6]
https://github.com/Ravinou/borgwarehouse/releases/tag/v2.1.0 Has been out since 2024-01-01

i.e. merge https://github.com/YunoHost-Apps/borgwarehouse_ynh/tree/ci-auto-update-2.1.0

**Comment by silverhook** [comment]
This is already the case in https://github.com/YunoHost-Apps/borgwarehouse_ynh/tree/testing

So the https://github.com/YunoHost-Apps/borgwarehouse_ynh/tree/ci-auto-update-2.1.0 can be removed, I think

**Comment by ericgaspar** [comment]
fixed
